"""
Temporal Graph Network (TGN) — Production Module
==================================================

Rewritten from scratch. Consumes ONLY the production outputs already
generated by the upstream pipeline stages:

    build_event_graph.py  -> graph/output/node_graph_skeleton.pt
                              graph/output/preprocessing_artifacts.pkl
    edge_features.py      -> graph/output/edge_feature_shards/<Relation>/edge_features_*.pt
    edge_weighting.py     -> (dynamic edge weight folded into the feature
                               shards above; see `_resolve_edge_weight`)

This module never touches `edge_shards/` or `edge_shard_manifest.json` —
those belong to graph construction, not to the TGN.

Run directly from the project root:

    python models/tgn_model.py

No sys.path manipulation, no PYTHONPATH, no dependency on a package
named "graph" — this file is fully self-contained and only imports
torch and the standard library.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Tuple, Union

import torch
import torch.nn as nn

# ======================================================================
# Logging
# ======================================================================

logger = logging.getLogger("tgn")
if not logger.handlers:
    _handler = logging.StreamHandler()
    _handler.setFormatter(
        logging.Formatter("%(asctime)s | %(levelname)-7s | %(name)s | %(message)s")
    )
    logger.addHandler(_handler)
logger.setLevel(logging.INFO)


# ======================================================================
# Config
# ======================================================================

@dataclass
class TGNConfig:
    """All dimensions are configurable; nothing below is hardcoded to a
    specific dataset or relation."""

    memory_dim: int = 128
    time_dim: int = 32
    embedding_dim: int = 128
    message_hidden_dim: int = 128
    aggregator: str = "attention"  # "last" | "mean" | "attention"
    device: Optional[str] = None  # None -> auto-detect CUDA / CPU

    def resolved_device(self) -> torch.device:
        if self.device is not None:
            return torch.device(self.device)
        return torch.device("cuda" if torch.cuda.is_available() else "cpu")


# ======================================================================
# Shard discovery (no hardcoded shard or relation names)
# ======================================================================

REQUIRED_SHARD_KEYS = {
    "edge_index",
    "features",
    "temporal_encoding",
    "edge_time",
    "feature_names",
    "feature_version",
    "relation",
    "src_node_type",
    "dst_node_type",
    "num_edges",
}


class ShardDiscovery:
    """Auto-discovers relation subdirectories and shard files under
    `<root>/edge_feature_shards/`. Never loads `edge_shards/` or
    `edge_shard_manifest.json` — those are graph-construction-only
    artifacts and are explicitly out of scope for the TGN."""

    def __init__(self, root: Union[str, Path]) -> None:
        self.root = Path(root)
        self.edge_feature_dir = self.root / "edge_feature_shards"
        if not self.edge_feature_dir.is_dir():
            raise FileNotFoundError(
                f"Expected production edge feature shards at "
                f"'{self.edge_feature_dir}' (output of edge_features.py). "
                f"Directory not found."
            )

    def discover_relations(self) -> List[str]:
        """Auto-discover valid production relation folders.

        A subdirectory is only treated as a relation if it (a) is not
        hidden/transient (no leading '.', not '__pycache__') and (b)
        actually contains at least one 'edge_features_*.pt' shard. This
        keeps discovery generic — no relation name is ever hardcoded —
        while excluding scratch directories such as '.tmp' that
        edge_features.py may leave behind during Pass-1.
        """
        ignored_names = {"__pycache__", ".git", ".cache"}
        relations: List[str] = []
        for entry in sorted(self.edge_feature_dir.iterdir()):
            if not entry.is_dir():
                continue
            if entry.name.startswith("."):
                continue
            if entry.name in ignored_names:
                continue
            if not any(entry.glob("edge_features_*.pt")):
                logger.info("Skipping non-relation directory (no shards found): %s", entry.name)
                continue
            relations.append(entry.name)

        if not relations:
            raise FileNotFoundError(
                f"No production relation subdirectories discovered in {self.edge_feature_dir}"
            )

        logger.info("Discovered %d production relation(s):\n%s", len(relations), "\n".join(relations))
        return relations

    def discover_shards(self, relation: str) -> List[Path]:
        relation_dir = self.edge_feature_dir / relation
        shards = sorted(relation_dir.glob("edge_features_*.pt"))
        if not shards:
            raise FileNotFoundError(f"No shard files found for relation '{relation}' in {relation_dir}")
        return shards

    def discover_all(self) -> Dict[str, List[Path]]:
        return {relation: self.discover_shards(relation) for relation in self.discover_relations()}


def load_shard(path: Path, device: torch.device) -> Dict[str, torch.Tensor]:
    """Load and validate a single production edge feature shard. Streaming
    friendly: only ever holds one shard in memory at a time."""
    logger.info("Loading shard: %s", path)
    raw = torch.load(path, map_location="cpu")
    if not isinstance(raw, dict):
        raise ValueError(f"Shard {path} did not contain a dict payload")

    missing = REQUIRED_SHARD_KEYS - set(raw.keys())
    if missing:
        raise ValueError(f"Shard {path} is missing required keys: {sorted(missing)}")

    edge_index = raw["edge_index"]
    features = raw["features"]
    temporal_encoding = raw["temporal_encoding"]
    edge_time = raw["edge_time"]

    if not torch.is_tensor(edge_index) or edge_index.dim() != 2 or edge_index.size(0) != 2:
        raise ValueError(f"Shard {path}: 'edge_index' must be a [2, E] tensor")
    if not torch.is_tensor(features) or features.dim() != 2:
        raise ValueError(f"Shard {path}: 'features' must be a [E, F] tensor")
    if not torch.is_tensor(temporal_encoding) or temporal_encoding.dim() != 2:
        raise ValueError(f"Shard {path}: 'temporal_encoding' must be a [E, T] tensor")
    if not torch.is_tensor(edge_time) or edge_time.dim() != 1:
        raise ValueError(f"Shard {path}: 'edge_time' must be a [E] tensor")

    num_edges_declared = int(raw["num_edges"])
    if edge_index.size(1) != num_edges_declared:
        logger.warning(
            "Shard %s declares num_edges=%d but edge_index has %d columns; "
            "trusting the tensor shape over the metadata field",
            path, num_edges_declared, edge_index.size(1),
        )

    out: Dict[str, torch.Tensor] = dict(raw)
    out["edge_index"] = edge_index.to(device=device, dtype=torch.long)
    out["features"] = features.to(device=device, dtype=torch.float32)
    out["temporal_encoding"] = temporal_encoding.to(device=device, dtype=torch.float32)
    out["edge_time"] = edge_time.to(device=device, dtype=torch.float32)
    if "edge_weight" in raw and torch.is_tensor(raw["edge_weight"]):
        out["edge_weight"] = raw["edge_weight"].to(device=device, dtype=torch.float32)
    return out


def _extract_num_nodes_from_skeleton(skeleton: object) -> Optional[int]:
    """Best-effort, schema-tolerant extraction of node count from
    node_graph_skeleton.pt. Tries several common encodings before giving up
    (the caller falls back to inferring the count from shard edge indices)."""
    if isinstance(skeleton, dict):
        for key in ("num_nodes", "num_nodes_total", "n_nodes", "total_nodes"):
            if key in skeleton:
                try:
                    return int(skeleton[key])
                except (TypeError, ValueError):
                    pass
        for key in ("node_id_map", "node_index", "node_ids", "node_to_id"):
            value = skeleton.get(key)
            if value is not None and hasattr(value, "__len__"):
                return len(value)
        max_id = -1
        for value in skeleton.values():
            if torch.is_tensor(value) and value.dtype in (torch.int64, torch.int32) and value.numel() > 0:
                try:
                    max_id = max(max_id, int(value.max().item()))
                except (RuntimeError, ValueError):
                    continue
        if max_id >= 0:
            return max_id + 1
    elif hasattr(skeleton, "num_nodes"):
        try:
            return int(skeleton.num_nodes)  # type: ignore[attr-defined]
        except (TypeError, ValueError):
            return None
    return None


def infer_num_nodes(root: Path, shard_paths: Dict[str, List[Path]]) -> int:
    """Resolve the total node count from node_graph_skeleton.pt when
    possible, cross-checked against the max node id seen while peeking at
    one shard per relation (cheap, streaming-safe — never loads the whole
    dataset)."""
    skeleton_path = root / "node_graph_skeleton.pt"
    from_skeleton: Optional[int] = None
    if skeleton_path.exists():
        try:
            skeleton = torch.load(skeleton_path, map_location="cpu")
            from_skeleton = _extract_num_nodes_from_skeleton(skeleton)
        except Exception as exc:  # noqa: BLE001 - defensive against unknown skeleton schema
            logger.warning("Could not parse node_graph_skeleton.pt (%s); falling back to shard inference", exc)
    else:
        logger.warning("node_graph_skeleton.pt not found at %s; inferring node count from shards", skeleton_path)

    max_id = -1
    for paths in shard_paths.values():
        peek_path = paths[0]
        raw = torch.load(peek_path, map_location="cpu")
        edge_index = raw.get("edge_index")
        if torch.is_tensor(edge_index) and edge_index.numel() > 0:
            max_id = max(max_id, int(edge_index.max().item()))
    from_shards = max_id + 1 if max_id >= 0 else None

    candidates = [v for v in (from_skeleton, from_shards) if v]
    if not candidates:
        raise RuntimeError(
            "Unable to determine number of nodes from node_graph_skeleton.pt or from shard edge indices."
        )
    num_nodes = max(candidates)
    logger.info("Resolved num_nodes=%d (skeleton=%s, shard_peek=%s)", num_nodes, from_skeleton, from_shards)
    return num_nodes


# ======================================================================
# Time Encoder
# ======================================================================

class TimeEncoder(nn.Module):
    """Learnable sinusoidal time encoding (Time2Vec-style, as used in the
    original TGN paper). Initialized to a geometric frequency spread so
    training starts from a sensible multi-scale basis, but every weight
    remains learnable."""

    def __init__(self, time_dim: int) -> None:
        super().__init__()
        self.time_dim = time_dim
        self.linear = nn.Linear(1, time_dim)
        with torch.no_grad():
            freq = 1.0 / torch.pow(10.0, torch.linspace(0, 9, time_dim))
            self.linear.weight.copy_(freq.view(time_dim, 1))
            self.linear.bias.zero_()

    def forward(self, delta_t: torch.Tensor) -> torch.Tensor:
        if delta_t.dim() == 1:
            delta_t = delta_t.view(-1, 1)
        return torch.cos(self.linear(delta_t))


# ======================================================================
# Memory Module
# ======================================================================

class MemoryModule(nn.Module):
    """Persistent, per-node memory with GRU-based updates.

    The memory tensor is a buffer (running state, not a trainable leaf),
    matching standard TGN practice: the GRUCell parameters are learned,
    but the memory values themselves are detached and explicitly
    overwritten between batches.
    """

    def __init__(self, num_nodes: int, memory_dim: int, message_dim: int) -> None:
        super().__init__()
        self.num_nodes = num_nodes
        self.memory_dim = memory_dim
        self.gru = nn.GRUCell(input_size=message_dim, hidden_size=memory_dim)
        self.register_buffer("memory", torch.zeros(num_nodes, memory_dim))
        self.register_buffer("last_update", torch.zeros(num_nodes))

    def get_memory(self, node_ids: torch.Tensor) -> torch.Tensor:
        return self.memory[node_ids]

    def get_last_update(self, node_ids: torch.Tensor) -> torch.Tensor:
        return self.last_update[node_ids]

    @torch.no_grad()
    def reset(self) -> None:
        self.memory.zero_()
        self.last_update.zero_()

    def compute_updated_memory(self, node_ids: torch.Tensor, aggregated_messages: torch.Tensor) -> torch.Tensor:
        """Compute new memory values WITHOUT committing them.

        Correctness requirement: this is called once per batch, for every
        affected node (source AND destination together), reading memory
        as it existed BEFORE this batch. Source updates must never see
        destination's in-batch update or vice versa — both are derived
        from the identical pre-batch snapshot.
        """
        pre_batch_memory = self.memory[node_ids]
        return self.gru(aggregated_messages, pre_batch_memory)

    @torch.no_grad()
    def commit(self, node_ids: torch.Tensor, new_memory: torch.Tensor, timestamps: torch.Tensor) -> None:
        """Atomically write updated memory for a (deduplicated) set of node
        ids. Must only be called after all reads for this batch are done."""
        self.memory[node_ids] = new_memory.detach()
        self.last_update[node_ids] = timestamps.detach()


# ======================================================================
# Message Function
# ======================================================================

class MessageFunction(nn.Module):
    """Combines source memory, destination memory, edge features
    (production rich features + precomputed temporal encoding from the
    upstream shard), a learned time encoding, and the dynamic edge weight
    into a single message vector."""

    def __init__(self, memory_dim: int, edge_feature_dim: int, time_dim: int, hidden_dim: int) -> None:
        super().__init__()
        input_dim = (memory_dim * 2) + edge_feature_dim + time_dim + 1  # +1: scalar dynamic edge weight
        self.mlp = nn.Sequential(
            nn.Linear(input_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, hidden_dim),
        )

    def forward(
        self,
        src_memory: torch.Tensor,
        dst_memory: torch.Tensor,
        edge_features: torch.Tensor,
        time_encoding: torch.Tensor,
        edge_weight: torch.Tensor,
    ) -> torch.Tensor:
        if edge_weight.dim() == 1:
            edge_weight = edge_weight.view(-1, 1)
        combined = torch.cat([src_memory, dst_memory, edge_features, time_encoding, edge_weight], dim=-1)
        return self.mlp(combined)


# ======================================================================
# Message Aggregator
# ======================================================================

class MessageAggregator(nn.Module):
    """Aggregates possibly-repeated per-edge messages into a single message
    per unique node. Supports 'last', 'mean', and 'attention'."""

    def __init__(self, message_dim: int, mode: str = "attention") -> None:
        super().__init__()
        if mode not in ("last", "mean", "attention"):
            raise ValueError(f"Unknown aggregator mode: {mode!r}. Expected 'last', 'mean', or 'attention'.")
        self.mode = mode
        self.message_dim = message_dim
        if mode == "attention":
            self.attn = nn.Linear(message_dim, 1)

    def forward(self, node_ids: torch.Tensor, messages: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor]:
        device = messages.device
        unique_ids, inverse = torch.unique(node_ids, return_inverse=True)
        num_unique = unique_ids.size(0)
        agg = torch.zeros(num_unique, self.message_dim, device=device, dtype=messages.dtype)

        if self.mode == "mean":
            counts = torch.zeros(num_unique, device=device, dtype=messages.dtype)
            agg.index_add_(0, inverse, messages)
            counts.index_add_(0, inverse, torch.ones_like(inverse, dtype=messages.dtype))
            agg = agg / counts.clamp(min=1).unsqueeze(-1)

        elif self.mode == "last":
            # Shards are chronologically ordered; index_copy_ processed in
            # ascending edge order means the final write per node id is the
            # most recent message for that node.
            agg.index_copy_(0, inverse, messages)

        else:  # attention
            scores = self.attn(messages).squeeze(-1)
            max_per_group = torch.full((num_unique,), float("-inf"), device=device, dtype=messages.dtype)
            max_per_group = max_per_group.scatter_reduce(0, inverse, scores, reduce="amax", include_self=True)
            shifted = scores - max_per_group[inverse]
            exp_scores = shifted.exp()
            denom = torch.zeros(num_unique, device=device, dtype=messages.dtype)
            denom.index_add_(0, inverse, exp_scores)
            weights = exp_scores / denom[inverse].clamp(min=1e-12)
            agg.index_add_(0, inverse, messages * weights.unsqueeze(-1))

        return unique_ids, agg


# ======================================================================
# Embedding Module
# ======================================================================

class EmbeddingModule(nn.Module):
    """Produces the final node embedding from memory, aggregated neighbor
    messages, and a time encoding — never from memory alone."""

    def __init__(self, memory_dim: int, message_dim: int, time_dim: int, embedding_dim: int) -> None:
        super().__init__()
        input_dim = memory_dim + message_dim + time_dim
        self.mlp = nn.Sequential(
            nn.Linear(input_dim, embedding_dim),
            nn.ReLU(),
            nn.Linear(embedding_dim, embedding_dim),
        )

    def forward(self, memory: torch.Tensor, neighbor_messages: torch.Tensor, time_encoding: torch.Tensor) -> torch.Tensor:
        combined = torch.cat([memory, neighbor_messages, time_encoding], dim=-1)
        return self.mlp(combined)


# ======================================================================
# Temporal Graph Network
# ======================================================================

class TemporalGraphNetwork(nn.Module):
    """Full TGN: memory + message function + aggregator + time encoder +
    embedding module, wired together with a correct batched memory update
    (all updates computed from one shared pre-batch snapshot, then
    committed together)."""

    def __init__(self, num_nodes: int, edge_feature_dim: int, config: Optional[TGNConfig] = None) -> None:
        super().__init__()
        self.config = config or TGNConfig()
        self.device = self.config.resolved_device()
        self.num_nodes = num_nodes
        self.edge_feature_dim = edge_feature_dim

        self.time_encoder = TimeEncoder(self.config.time_dim)
        self.memory = MemoryModule(num_nodes, self.config.memory_dim, self.config.message_hidden_dim)
        self.message_fn = MessageFunction(
            self.config.memory_dim, edge_feature_dim, self.config.time_dim, self.config.message_hidden_dim
        )
        self.aggregator = MessageAggregator(self.config.message_hidden_dim, mode=self.config.aggregator)
        self.embedding_module = EmbeddingModule(
            self.config.memory_dim, self.config.message_hidden_dim, self.config.time_dim, self.config.embedding_dim
        )

        self.to(self.device)
        logger.info(
            "Initialized TGN | num_nodes=%d edge_feature_dim=%d memory_dim=%d time_dim=%d "
            "embedding_dim=%d aggregator=%s device=%s",
            num_nodes, edge_feature_dim, self.config.memory_dim, self.config.time_dim,
            self.config.embedding_dim, self.config.aggregator, self.device,
        )

    def _resolve_edge_weight(self, shard: Dict[str, torch.Tensor]) -> torch.Tensor:
        """Dynamic edge weighting (edge_weighting.py) is expected to have
        been folded into the production shard already. If an explicit
        `edge_weight` field is present we use it directly; otherwise we
        fall back to the L2 norm of the rich feature vector as a bounded
        scalar proxy — computed from real production features, never
        fabricated."""
        if "edge_weight" in shard and torch.is_tensor(shard["edge_weight"]):
            return shard["edge_weight"].to(self.device)
        return shard["features"].norm(dim=-1)

    def process_shard(self, shard: Dict[str, torch.Tensor]) -> Dict[str, torch.Tensor]:
        """One full TGN forward pass over a single streamed edge feature
        shard: message computation -> aggregation -> memory update
        (batched, from a shared pre-batch snapshot) -> embedding."""
        edge_index = shard["edge_index"].to(self.device)
        features = shard["features"].to(self.device)
        temporal_encoding = shard["temporal_encoding"].to(self.device)
        edge_time = shard["edge_time"].to(device=self.device, dtype=torch.float32)
        edge_weight = self._resolve_edge_weight(shard)

        # Rich edge features = production features concatenated with the
        # precomputed temporal encoding already present on the shard.
        # (Distinct from this module's own learnable recency encoding
        # below, which encodes *time since last update* per node.)
        combined_edge_features = torch.cat([features, temporal_encoding], dim=-1)

        src, dst = edge_index[0], edge_index[1]

        src_last_update = self.memory.get_last_update(src)
        dst_last_update = self.memory.get_last_update(dst)
        src_delta_t = (edge_time - src_last_update).clamp(min=0)
        dst_delta_t = (edge_time - dst_last_update).clamp(min=0)

        src_time_enc = self.time_encoder(src_delta_t)
        dst_time_enc = self.time_encoder(dst_delta_t)

        # --- Pre-batch memory snapshot, shared by both directions. ---
        src_memory_pre = self.memory.get_memory(src)
        dst_memory_pre = self.memory.get_memory(dst)

        # An interaction informs BOTH endpoints (standard TGN treatment).
        msg_for_dst = self.message_fn(src_memory_pre, dst_memory_pre, combined_edge_features, dst_time_enc, edge_weight)
        msg_for_src = self.message_fn(dst_memory_pre, src_memory_pre, combined_edge_features, src_time_enc, edge_weight)

        all_node_ids = torch.cat([dst, src], dim=0)
        all_messages = torch.cat([msg_for_dst, msg_for_src], dim=0)
        all_times = torch.cat([edge_time, edge_time], dim=0)

        unique_ids, aggregated_messages = self.aggregator(all_node_ids, all_messages)

        # Track the most recent contributing timestamp per unique node,
        # independent of which message-aggregation mode is configured.
        _, inverse_for_time = torch.unique(all_node_ids, return_inverse=True)
        latest_time = torch.full((unique_ids.size(0),), float("-inf"), device=self.device)
        latest_time = latest_time.scatter_reduce(0, inverse_for_time, all_times, reduce="amax", include_self=True)

        # --- Compute (do not yet commit) updated memory for ALL affected
        # nodes together, from the identical pre-batch state. ---
        new_memory = self.memory.compute_updated_memory(unique_ids, aggregated_messages)

        # Embedding depends on memory + neighbor messages + time encoding —
        # never on memory alone.
        zero_delta = torch.zeros(unique_ids.size(0), device=self.device)
        neighbor_time_enc = self.time_encoder(zero_delta)
        embeddings = self.embedding_module(self.memory.get_memory(unique_ids), aggregated_messages, neighbor_time_enc)

        # --- Commit AFTER every read/computation above is finished. ---
        self.memory.commit(unique_ids, new_memory, latest_time)

        if torch.isnan(embeddings).any():
            raise RuntimeError("NaN detected in computed embeddings")
        if torch.isnan(self.memory.memory).any():
            raise RuntimeError("NaN detected in memory after commit")

        return {
            "updated_node_ids": unique_ids,
            "embeddings": embeddings,
            "num_edges": torch.tensor(edge_index.size(1)),
        }

    def _validate_feature_dim(self, shard: Dict[str, torch.Tensor]) -> None:
        actual_dim = shard["features"].size(-1) + shard["temporal_encoding"].size(-1)
        if actual_dim != self.edge_feature_dim:
            raise ValueError(
                f"Shard combined feature dim {actual_dim} does not match model "
                f"edge_feature_dim {self.edge_feature_dim} (relation='{shard.get('relation')}')"
            )

    def run_over_root(self, root: Union[str, Path]) -> None:
        """Stream every discovered shard, one at a time, through the
        network. Never loads the entire dataset into memory."""
        discovery = ShardDiscovery(root)
        shard_map = discovery.discover_all()
        for relation, paths in shard_map.items():
            logger.info("Processing relation '%s' (%d shard(s))", relation, len(paths))
            for path in paths:
                shard = load_shard(path, self.device)
                self._validate_feature_dim(shard)
                result = self.process_shard(shard)
                logger.info(
                    "relation=%s shard=%s edges=%d updated_nodes=%d",
                    relation, path.name, int(result["num_edges"]), result["updated_node_ids"].numel(),
                )


def build_tgn_from_root(
    root: Union[str, Path], config: Optional[TGNConfig] = None
) -> Tuple[TemporalGraphNetwork, Dict[str, List[Path]]]:
    """Factory: discovers shards under `root`, infers dimensions from the
    real production data (no hardcoded shard/relation names, no
    hardcoded feature width), and constructs a ready-to-use TGN."""
    root = Path(root)
    discovery = ShardDiscovery(root)
    shard_map = discovery.discover_all()

    first_relation = next(iter(shard_map))
    first_shard_path = shard_map[first_relation][0]
    probe = torch.load(first_shard_path, map_location="cpu")
    edge_feature_dim = int(probe["features"].size(-1)) + int(probe["temporal_encoding"].size(-1))

    num_nodes = infer_num_nodes(root, shard_map)

    model = TemporalGraphNetwork(num_nodes=num_nodes, edge_feature_dim=edge_feature_dim, config=config)
    return model, shard_map


# ======================================================================
# Production self-test
# ======================================================================

def _self_test() -> None:
    """Discovers real production shards under graph/output/, runs one
    forward pass on the first shard found, and verifies edge count,
    memory update, embedding size, absence of NaN, and device
    consistency. No fabricated data, no synthetic shortcuts."""
    project_root = Path(__file__).resolve().parent.parent
    graph_output_root = project_root / "graph" / "output"

    logger.info("=" * 70)
    logger.info("TGN PRODUCTION SELF-TEST")
    logger.info("root=%s", graph_output_root)
    logger.info("=" * 70)

    config = TGNConfig()
    model, shard_map = build_tgn_from_root(graph_output_root, config)
    model.eval()

    first_relation = next(iter(shard_map))
    first_shard_path = shard_map[first_relation][0]
    shard = load_shard(first_shard_path, model.device)
    model._validate_feature_dim(shard)

    declared_edges = shard["edge_index"].size(1)

    with torch.no_grad():
        result = model.process_shard(shard)

    embeddings = result["embeddings"]
    updated_ids = result["updated_node_ids"]

    assert int(result["num_edges"]) == declared_edges, "Edge count mismatch"
    assert embeddings.size(0) == updated_ids.size(0), "Embedding count must match updated node count"
    assert embeddings.size(1) == config.embedding_dim, (
        f"Embedding dim {embeddings.size(1)} != configured {config.embedding_dim}"
    )
    assert not torch.isnan(embeddings).any(), "NaN detected in output embeddings"
    assert not torch.isnan(model.memory.memory).any(), "NaN detected in memory after update"
    assert embeddings.device.type == model.device.type, "Device mismatch between embeddings and model"
    assert updated_ids.numel() > 0, "No nodes were updated"

    logger.info("relation=%s shard=%s", first_relation, first_shard_path.name)
    logger.info("edge_count=%d", declared_edges)
    logger.info("updated_nodes=%d", updated_ids.numel())
    logger.info("embedding_shape=%s", tuple(embeddings.shape))
    logger.info("memory_shape=%s", tuple(model.memory.memory.shape))
    logger.info("device=%s", model.device)
    logger.info("PASS")


if __name__ == "__main__":
    _self_test()
# Backward compatibility
TGN = TemporalGraphNetwork